import UuidPage from '@/tools/uuid';
import { INavCategory, INavItem } from '@/common/interfaces';
import { appConfig } from './app.constant';
import JsonFormatterTool from '@/tools/json-formatter';
import Base64TextEncoderDecoderTool from '@/tools/base64-text-encoder-decoder';
import JwtTool from '@/tools/jwt';
import EpochTool from '@/tools/epoch';
import JsonToCsvTool from '@/tools/json-to-csv';
import PasswordGeneratorTool from '@/tools/password';
import SqlFormatterTool from '@/tools/sql-formatter';
import Base64FileTool from '@/tools/base64-file';

export const navCategories: Record<string, INavCategory> = {
  generators: {
    id: 'generators',
    name: 'Generators',
    route: '/generators',
    visibleOnSidebar: true,
    description:
      'Effortlessly create essential data for your development projects.',
  },
  formatters: {
    id: 'formatters',
    name: 'Formatters',
    route: '/formatters',
    visibleOnSidebar: true,
    description:
      'Simplify your development workflow with tools to format and structure your data effortlessly.',
  },
  'encoders-decoders': {
    id: 'encoders-decoders',
    name: 'Encoders / Decoders',
    route: '/encoders-decoders',
    visibleOnSidebar: true,
    description:
      'Convert your data seamlessly with our Encoders and Decoders. Effortlessly encode or decode text, files, and other formats to suit your development needs.',
  },
  converters: {
    id: 'converters',
    name: 'Converters',
    route: '/converters',
    visibleOnSidebar: true,
    description:
      'Quickly transform data between various formats with our versatile Converters.',
  },
  links: {
    id: 'links',
    name: 'Links',
    route: '/links',
    visibleOnSidebar: false,
    description: 'Other Links',
  },
};

export const navItems: INavItem[] = [
  // generators
  {
    id: 'uuid-generator',
    category: navCategories.generators.id,
    icon: 'far fa-fw fa-hashtag',
    name: 'UUID',
    pageTitle: 'UUID Generator',
    description:
      'Quickly generate universally unique identifiers (UUIDs) in various versions and configurations to meet your specific requirements.',
    route: `${navCategories.generators.route}/uuid-generator`,
    visibleOnSidebar: true,
    page: UuidPage,
    keywords: [
      'uuid',
      'uuid generator',
      'uuid v4',
      'uuid v5',
      'uuid v6',
      'uuid v7',
      'uuid v8',
      'UUID generator',
      'online UUID generator',
      'generate UUID',
      'UUID generator tool',
      'UUID version 4 generator',
      'free UUID generator',
      'UUID creation',
      'unique identifier generator',
      'v4 UUID generator',
      'random UUID generator',
      'UUID generator for developers',
      'UUID tool online',
    ],
  },

  {
    id: 'password-generator',
    category: navCategories.generators.id,
    icon: 'far fa-fw fa-key',
    name: 'Password Generator',
    pageTitle: 'Password Generator',
    description:
      'Effortlessly create strong, random passwords to protect sensitive data with our advanced password generation tool.',
    route: `${navCategories.generators.route}/password-generator`,
    visibleOnSidebar: true,
    page: PasswordGeneratorTool,
    keywords: [
      'password',
      'password generator',
      'password generator tool',
      'password generator online',
      'strong passwords',
      'random password generator',
      'secure passwords',
      'online password generator',
      'password creation tool',
      'free password generator',
      'password security',
      'password tool online',
    ],
  },

  // formatters
  {
    id: 'json-formatter',
    category: navCategories.formatters.id,
    icon: 'far fa-fw fa-brackets-curly',
    name: 'JSON Formatter',
    pageTitle: 'JSON Formatter',
    description:
      'Easily format, minify, and beautify JSON data for improved readability and optimized usage.',
    route: `${navCategories.formatters.route}/json-formatter`,
    visibleOnSidebar: true,
    page: JsonFormatterTool,
    keywords: [
      'json',
      'json formatter',
      'json beautifier',
      'json minifier',
      'JSON formatter',
      'online JSON formatter',
      'format JSON',
      'JSON beautifier',
      'JSON minifier',
      'JSON viewer',
      'JSON prettifier',
      'free JSON formatter',
      'JSON formatting tool',
      'JSON parser',
      'beautify JSON online',
      'minify JSON online',
      'JSON formatter for developers',
      'JSON tool online',
    ],
  },
  {
    id: 'sql-formatter',
    category: navCategories.formatters.id,
    icon: 'far fa-fw fa-code',
    name: 'SQL Formatter',
    pageTitle: 'SQL Formatter',
    description:
      'Refine your SQL queries for improved readability and consistency with our intuitive SQL formatting tool.',
    route: `${navCategories.formatters.route}/sql-formatter`,
    visibleOnSidebar: true,
    page: SqlFormatterTool,
    keywords: [
      'sql',
      'sql formatter',
      'sql beautifier',
      'sql minifier',
      'SQL formatter',
      'online SQL formatter',
      'format SQL',
      'SQL minifier',
      'SQL viewer',
      'SQL prettifier',
      'SQL formatter',
      'format SQL queries',
      'SQL beautifier',
      'SQL formatting tool',
      'improve SQL readability',
      'clean up SQL code',
      'SQL query consistency',
      'SQL syntax tool',
      'SQL tool online',
    ],
  },

  // encoders-decoders
  {
    id: 'base64-text-encoder-decoder',
    category: navCategories['encoders-decoders'].id,
    icon: 'far fa-fw fa-file-word',
    name: 'Base64 Text',
    pageTitle: 'Base64 Text Encoder and Decoder',
    description:
      'Effortlessly encode and decode text using Base64 encoding for secure and efficient data handling.',
    route: `${navCategories['encoders-decoders'].route}/base64-text-encoder-decoder`,
    visibleOnSidebar: true,
    page: Base64TextEncoderDecoderTool,
    keywords: [
      'base64',
      'base64 encoder',
      'base64 decoder',
      'base64 encoding',
      'base64 decoding',
      'Base64 text encoder',
      'Base64 text decoder',
      'encode text to Base64',
      'decode Base64 to text',
      'online Base64 encoder',
      'online Base64 decoder',
      'Base64 conversion tool',
      'text to Base64 converter',
      'free Base64 encoder',
      'free Base64 decoder',
      'Base64 tool online',
      'Base64 utility for developers',
    ],
  },

  {
    id: 'base64-file-encoder-decoder',
    category: navCategories['encoders-decoders'].id,
    icon: 'far fa-fw fa-file',
    name: 'Base64 File',
    pageTitle: 'Base64 File Encoder and Decoder',
    description:
      'Convert files to Base64 and decode Base64 strings back to files. Preview Base64 encoded images directly.',
    route: `${navCategories['encoders-decoders'].route}/base64-file-encoder-decoder`,
    visibleOnSidebar: true,
    page: Base64FileTool,
    keywords: [
      'base64 file',
      'base64 file encoder',
      'base64 file decoder',
      'file to base64',
      'base64 to file',
      'base64 image preview',
      'base64 file converter',
      'encode file to base64',
      'decode base64 to file',
      'base64 image encoder',
      'base64 image decoder',
      'file base64 conversion',
      'online base64 file converter',
      'base64 file utility',
      'base64 file tool',
    ],
  },

  {
    id: 'jwt-encoder-decoder',
    category: navCategories['encoders-decoders'].id,
    icon: 'far fa-fw fa-key',
    name: 'JWT',
    pageTitle: 'JWT Encoder and Decoder',
    description:
      'Encode and decode JSON Web Tokens (JWT). Easily inspect JWT headers, payloads, and signatures.',
    route: `${navCategories['encoders-decoders'].route}/jwt-encoder-decoder`,
    visibleOnSidebar: true,
    page: JwtTool,
    keywords: [
      'jwt',
      'jwt decoder',
      'jwt encoder',
      'json web token',
      'jwt parser',
      'decode jwt',
      'encode jwt',
      'jwt inspector',
      'jwt validator',
      'jwt tool',
      'jwt debugger',
      'jwt generator',
      'jwt creator',
      'jwt viewer',
      'jwt analyzer',
      'online jwt decoder',
      'online jwt encoder',
      'jwt tool for developers',
    ],
  },

  // converters

  {
    id: 'epoch-converter',
    category: navCategories.converters.id,
    icon: 'far fa-fw fa-clock',
    name: 'Epoch Converter',
    pageTitle: 'Epoch Converter',
    description:
      'Convert between epoch timestamps and human-readable dates. Calculate time durations and get current epoch time.',
    route: `${navCategories.converters.route}/epoch-converter`,
    visibleOnSidebar: true,
    page: EpochTool,
    keywords: [
      'epoch',
      'epoch converter',
      'unix timestamp',
      'timestamp converter',
      'epoch to date',
      'date to epoch',
      'unix time',
      'timestamp to date',
      'current epoch',
      'epoch calculator',
      'time converter',
      'unix epoch',
      'epoch time',
      'milliseconds to date',
      'seconds to date',
      'time duration calculator',
      'epoch to human readable',
      'timestamp tool',
    ],
  },

  {
    id: 'json-to-csv-converter',
    category: navCategories.converters.id,
    icon: 'far fa-fw fa-file-csv',
    name: 'JSON to CSV',
    pageTitle: 'JSON to CSV Converter',
    description:
      'Convert JSON data to CSV format. Easily transform JSON arrays into downloadable CSV files.',
    route: `${navCategories.converters.route}/json-to-csv-converter`,
    visibleOnSidebar: true,
    page: JsonToCsvTool,
    keywords: [
      'json to csv',
      'csv converter',
      'json converter',
      'json to csv converter',
      'convert json to csv',
      'json array to csv',
      'json data converter',
      'csv export',
      'json transformation',
      'online json to csv',
      'free json to csv converter',
      'json to csv tool',
      'csv generator',
      'json to spreadsheet',
      'data conversion tool',
      'json to excel',
      'convert json data',
      'csv transformation',
    ],
  },

  // links
  {
    id: 'about',
    category: navCategories.links.id,
    icon: 'fa-info-circle',
    name: 'About',
    pageTitle: `About | ${appConfig.name}`,
    description: `About ${appConfig.name}`,
    route: '/about',
    visibleOnSidebar: false,
    keywords: [
      'about',
      'about devease',
      'about tool',
      'about tools',
      'about dev tools',
      'devease',
      'devease tools',
      'devease website',
    ],
  },
  {
    id: 'github',
    category: navCategories.links.id,
    icon: 'fab fa-github',
    name: 'GitHub',
    pageTitle: 'GitHub',
    description: 'GitHub Repository',
    externalLink: 'https://github.com/mgoyal98/dev-ease',
    visibleOnSidebar: false,
  },
  {
    id: 'linkedin',
    category: navCategories.links.id,
    icon: 'fab fa-linkedin',
    name: 'LinkedIn',
    pageTitle: 'LinkedIn',
    description: 'LinkedIn Profile',
    externalLink: 'https://www.linkedin.com/in/madhur-goyal/',
    visibleOnSidebar: false,
  },
  {
    id: 'developer',
    category: navCategories.links.id,
    icon: 'fa-user',
    name: 'Developer',
    pageTitle: 'Developer',
    description: 'Developer Profile',
    externalLink: 'https://mgoyal.com',
    visibleOnSidebar: false,
  },
  {
    id: 'buy-me-coffee',
    category: navCategories.links.id,
    icon: 'fad fa-mug-hot',
    name: 'Buy Me a Coffee',
    pageTitle: 'Buy Me a Coffee',
    description: 'Support the development of this site',
    externalLink: 'https://razorpay.me/@mgoyal',
    visibleOnSidebar: false,
  },
];
