import UuidPage from '@/tools/uuid';
import { INavCategory, INavItem } from '@/common/interfaces';
import { appConfig } from './app.constant';
import JsonFormatterTool from '@/tools/json-formatter';
import Base64TextEncoderDecoderTool from '@/tools/base64-text-encoder-decoder';
import JwtTool from '@/tools/jwt';
import EpochTool from '@/tools/epoch';

export const navCategories: Record<string, INavCategory> = {
  generators: {
    id: 'generators',
    name: 'Generators',
    route: '/generators',
    visibleOnSidebar: true,
    description:
      'Effortlessly create essential data for your development projects.',
  },
  formatters: {
    id: 'formatters',
    name: 'Formatters',
    route: '/formatters',
    visibleOnSidebar: true,
    description:
      'Simplify your development workflow with tools to format and structure your data effortlessly.',
  },
  'encoders-decoders': {
    id: 'encoders-decoders',
    name: 'Encoders / Decoders',
    route: '/encoders-decoders',
    visibleOnSidebar: true,
    description:
      'Convert your data seamlessly with our Encoders and Decoders. Effortlessly encode or decode text, files, and other formats to suit your development needs.',
  },
  converters: {
    id: 'converters',
    name: 'Converters',
    route: '/converters',
    visibleOnSidebar: true,
    description:
      'Quickly transform data between various formats with our versatile Converters.',
  },
  links: {
    id: 'links',
    name: 'Links',
    route: '/links',
    visibleOnSidebar: false,
    description: 'Other Links',
  },
};

export const navItems: INavItem[] = [
  // generators
  {
    id: 'uuid',
    category: navCategories.generators.id,
    icon: 'far fa-fw fa-hashtag',
    name: 'UUID',
    pageTitle: 'UUID Generator',
    description:
      'Quickly generate universally unique identifiers (UUIDs) in various versions and configurations to meet your specific requirements.',
    route: `${navCategories.generators.route}/uuid`,
    visibleOnSidebar: true,
    page: UuidPage,
    keywords: [
      'uuid',
      'uuid generator',
      'uuid v4',
      'uuid v5',
      'uuid v6',
      'uuid v7',
      'uuid v8',
      'UUID generator',
      'online UUID generator',
      'generate UUID',
      'UUID generator tool',
      'UUID version 4 generator',
      'free UUID generator',
      'UUID creation',
      'unique identifier generator',
      'v4 UUID generator',
      'random UUID generator',
      'UUID generator for developers',
      'UUID tool online',
    ],
  },

  // formatters
  {
    id: 'json',
    category: navCategories.formatters.id,
    icon: 'far fa-fw fa-brackets-curly',
    name: 'JSON Formatter',
    pageTitle: 'JSON Formatter',
    description:
      'Easily format, minify, and beautify JSON data for improved readability and optimized usage.',
    route: `${navCategories.formatters.route}/json`,
    visibleOnSidebar: true,
    page: JsonFormatterTool,
    keywords: [
      'json',
      'json formatter',
      'json beautifier',
      'json minifier',
      'JSON formatter',
      'online JSON formatter',
      'format JSON',
      'JSON beautifier',
      'JSON minifier',
      'JSON viewer',
      'JSON prettifier',
      'free JSON formatter',
      'JSON formatting tool',
      'JSON parser',
      'beautify JSON online',
      'minify JSON online',
      'JSON formatter for developers',
      'JSON tool online',
    ],
  },

  // encoders-decoders
  {
    id: 'base64-text',
    category: navCategories['encoders-decoders'].id,
    icon: 'far fa-fw fa-file-word',
    name: 'Base64 Text',
    pageTitle: 'Base64 Text Encoder and Decoder',
    description:
      'Effortlessly encode and decode text using Base64 encoding for secure and efficient data handling.',
    route: `${navCategories['encoders-decoders'].route}/base64-text`,
    visibleOnSidebar: true,
    page: Base64TextEncoderDecoderTool,
    keywords: [
      'base64',
      'base64 encoder',
      'base64 decoder',
      'base64 encoding',
      'base64 decoding',
      'Base64 text encoder',
      'Base64 text decoder',
      'encode text to Base64',
      'decode Base64 to text',
      'online Base64 encoder',
      'online Base64 decoder',
      'Base64 conversion tool',
      'text to Base64 converter',
      'free Base64 encoder',
      'free Base64 decoder',
      'Base64 tool online',
      'Base64 utility for developers',
    ],
  },

  {
    id: 'jwt',
    category: navCategories['encoders-decoders'].id,
    icon: 'far fa-fw fa-key',
    name: 'JWT',
    pageTitle: 'JWT Encoder and Decoder',
    description:
      'Encode and decode JSON Web Tokens (JWT). Easily inspect JWT headers, payloads, and signatures.',
    route: `${navCategories['encoders-decoders'].route}/jwt`,
    visibleOnSidebar: true,
    page: JwtTool,
    keywords: [
      'jwt',
      'jwt decoder',
      'jwt encoder',
      'json web token',
      'jwt parser',
      'decode jwt',
      'encode jwt',
      'jwt inspector',
      'jwt validator',
      'jwt tool',
      'jwt debugger',
      'jwt generator',
      'jwt creator',
      'jwt viewer',
      'jwt analyzer',
      'online jwt decoder',
      'online jwt encoder',
      'jwt tool for developers',
    ],
  },

  // converters

  {
    id: 'epoch',
    category: navCategories.converters.id,
    icon: 'far fa-fw fa-clock',
    name: 'Epoch Converter',
    pageTitle: 'Epoch Converter',
    description:
      'Convert between epoch timestamps and human-readable dates. Calculate time durations and get current epoch time.',
    route: `${navCategories.converters.route}/epoch`,
    visibleOnSidebar: true,
    page: EpochTool,
    keywords: [
      'epoch',
      'epoch converter',
      'unix timestamp',
      'timestamp converter',
      'epoch to date',
      'date to epoch',
      'unix time',
      'timestamp to date',
      'current epoch',
      'epoch calculator',
      'time converter',
      'unix epoch',
      'epoch time',
      'milliseconds to date',
      'seconds to date',
      'time duration calculator',
      'epoch to human readable',
      'timestamp tool',
    ],
  },

  // links
  {
    id: 'about',
    category: navCategories.links.id,
    icon: 'fa-info-circle',
    name: 'About',
    pageTitle: `About | ${appConfig.name}`,
    description: `About ${appConfig.name}`,
    route: '/about',
    visibleOnSidebar: false,
    keywords: [
      'about',
      'about devease',
      'about tool',
      'about tools',
      'about dev tools',
      'devease',
      'devease tools',
      'devease website',
    ],
  },
  {
    id: 'github',
    category: navCategories.links.id,
    icon: 'fab fa-github',
    name: 'GitHub',
    pageTitle: 'GitHub',
    description: 'GitHub Repository',
    externalLink: 'https://github.com/mgoyal98',
    visibleOnSidebar: false,
  },
  {
    id: 'linkedin',
    category: navCategories.links.id,
    icon: 'fab fa-linkedin',
    name: 'LinkedIn',
    pageTitle: 'LinkedIn',
    description: 'LinkedIn Profile',
    externalLink: 'https://www.linkedin.com/in/madhur-goyal/',
    visibleOnSidebar: false,
  },
  {
    id: 'developer',
    category: navCategories.links.id,
    icon: 'fa-user',
    name: 'Developer',
    pageTitle: 'Developer',
    description: 'Developer Profile',
    externalLink: 'https://mgoyal.com',
    visibleOnSidebar: false,
  },
  {
    id: 'buy-me-coffee',
    category: navCategories.links.id,
    icon: 'fad fa-mug-hot',
    name: 'Buy Me a Coffee',
    pageTitle: 'Buy Me a Coffee',
    description: 'Support the development of this site',
    externalLink: 'https://razorpay.me/@mgoyal',
    visibleOnSidebar: false,
  },
];
