export enum StorageKeys {
  ColorMode = 'color-mode-v1',
  SidebarCollapsedItems = 'sidebar-collapsed-items-v1',
  SidebarOpen = 'sidebar-open-v1',
  UuidConfigs = 'uuid-configs-v1',
  JsonFormatterConfigs = 'json-formatter-configs-v1',
  Base64TextEncoderDecoderConfigs = 'base64-text-encoder-decoder-configs-v1',
  JwtConfigs = 'jwt-configs-v1',
  EpochConfigs = 'epoch-configs-v1',
  JsonToCsvConfigs = 'json-to-csv-configs-v1',
  PasswordConfigs = 'password-configs-v1',
  SqlFormatterConfigs = 'sql-formatter-configs-v1',
  HtmlPreviewConfigs = 'html-preview-configs-v1',
  UrlEncoderDecoderConfigs = 'url-encoder-decoder-configs-v1',
  RegexTesterConfigs = 'regex-tester-configs-v1',
  JsonCompareConfigs = 'json-compare-configs-v1',
  MarkdownPreviewConfigs = 'markdown-preview-configs-v1',
}
